[package]
name = "proba_negative_asset"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
clap = { version = "4.5.31", features = ["derive"] }
num-integer = "0.1.46"
rand = "0.9.0"
rand_distr = "0.5.1"
