[project]
name = "pdevnet"
version = "0.1.0"
description = "Sequence regression and classification networks based on path developments"
requires-python = ">=3.9"
dependencies = [
    "aeon==1.0.0",
    "matplotlib",
    "numpy<2.0.0",
    "pandas",
    "pydantic",
    "torch==1.9.0",
    "tqdm",
]
