[project]
name = "burn-cifar-10-converted"
version = "0.1.0"
description = "Python environment specification to fetch CIFAR10 dataset from neighbouring folder"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.2",
]
