[project]
name = "self-attention-block"
version = "0.1.0"
description = "Implement dot-product self-attention from scratch"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flax>=0.12.0",
    "jax>=0.7.2",
]
